sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - ANSIBLE=2.4
  - ANSIBLE=2.5
  - ANSIBLE=2.6
  - ANSIBLE=2.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env: ANSIBLE=2.4
    - python: 3.7
      dist: xenial
      sudo: true
      env: ANSIBLE=2.5
    - python: 3.7
      dist: xenial
      sudo: true
      env: ANSIBLE=2.6
    - python: 3.7
      dist: xenial
      sudo: true
      env: ANSIBLE=2.7
  fast_finish: true
install: pip install tox-travis
script:
  - tox
